package com.snaptools.snaptoolkit;

import java.util.HashMap;
import java.util.Locale;

public class Strings {

    private static final HashMap<String, HashMap<String, String>> data = new HashMap<>();

    static {
        // English (default)
        add("en", new String[][]{
            {"no_text",         "No text selected"},
            {"error",           "Error"},
            {"copied",          "Copied"},
            {"close",           "Close"},
            {"save",            "Save"},
            {"saved",           "Saved to Downloads"},
            {"shortening",      "Shortening URL..."},
            {"shorten_error",   "Failed to shorten URL"},
            {"translating",     "Translating..."},
            {"translate_error", "Translation failed"},
            {"computing",       "Computing..."},
            {"hash_copied",     "MD5 & SHA256 copied"},
            {"case_title",      "Change Case"},
            {"uppercase",       "UPPERCASE"},
            {"lowercase",       "lowercase"},
            {"titlecase",       "Title Case"},
            {"sentencecase",    "Sentence case"},
            {"looking_up",      "Looking up..."},
            {"ip_error",        "Could not fetch IP info"},
            {"generating_qr",   "Generating QR..."},
            {"qr_error",        "Failed to generate QR"},
            {"select_format",   "Convert to"},
            {"converting",      "Converting..."},
            {"convert_done",    "Converted and saved"},
            {"convert_error",   "Conversion failed"},
            {"no_valid_url",    "Not a valid URL"},
            {"words",           "Words"},
            {"assist_translate", "Translate"},
            {"assist_count",     "Count"},
            {"assist_hash",      "Hash"},
            {"assist_url",       "URL"},
            {"assist_ip",        "IP"},
            {"assist_qr",        "QR"},
            {"assist_screenshot", "Screenshot"},
            {"assist_menu_title", "Snap Assist"},
            {"assist_hint_swipe", "Swipe with 3 fingers to open Snap Assist"},
            {"assist_hint_button", "Use Accessibility button to open Snap Assist"},
            {"assist_hint_wave", "Wave your hand twice over the screen to open Snap Assist"},
            {"assist_no_proximity", "No proximity sensor detected on this device"},
            {"assist_hint_volume", "Press Volume Up twice quickly to open Snap Assist"},
            {"assist_trigger_volume", "Snap Assist opened from volume shortcut"},
            {"assist_triggered", "Snap Assist activated"},
            {"assist_ocr_empty", "No visible text found on screen"},
            {"assist_select_text_first", "Select text first, then run the tool"},
            {"assist_invalid_ip", "Selected text is not a valid IP/host"},
            {"assist_screenshot_taking", "Taking screenshot..."},
            {"assist_screenshot_saved", "Screenshot saved to Pictures/SnapToolKit"},
            {"assist_screenshot_failed", "Screenshot capture failed"},
            {"assist_screenshot_unsupported", "Screenshot requires Android 11 or newer"},
        });

        // Arabic
        add("ar", new String[][]{
            {"no_text",         "لا يوجد نص محدد"},
            {"error",           "خطأ"},
            {"copied",          "تم النسخ"},
            {"close",           "إغلاق"},
            {"save",            "حفظ"},
            {"saved",           "تم الحفظ في التنزيلات"},
            {"shortening",      "جاري تقصير الرابط..."},
            {"shorten_error",   "تعذر تقصير الرابط"},
            {"translating",     "جاري الترجمة..."},
            {"translate_error", "فشلت الترجمة"},
            {"computing",       "جاري الحساب..."},
            {"hash_copied",     "تم نسخ MD5 و SHA256"},
            {"case_title",      "تغيير حالة النص"},
            {"uppercase",       "أحرف كبيرة"},
            {"lowercase",       "أحرف صغيرة"},
            {"titlecase",       "تكبير كل كلمة"},
            {"sentencecase",    "بداية الجملة"},
            {"looking_up",      "جاري البحث..."},
            {"ip_error",        "تعذر جلب معلومات IP"},
            {"generating_qr",   "جاري توليد QR..."},
            {"qr_error",        "تعذر توليد QR"},
            {"select_format",   "تحويل إلى"},
            {"converting",      "جاري التحويل..."},
            {"convert_done",    "تم التحويل والحفظ"},
            {"convert_error",   "فشل التحويل"},
            {"no_valid_url",    "ليس رابطاً صحيحاً"},
            {"words",           "كلمات"},
            {"assist_translate", "ترجمة"},
            {"assist_count",     "إحصاء"},
            {"assist_hash",      "تجزئة"},
            {"assist_url",       "رابط"},
            {"assist_ip",        "IP"},
            {"assist_qr",        "QR"},
            {"assist_screenshot", "لقطة شاشة"},
            {"assist_menu_title", "Snap Assist"},
            {"assist_hint_swipe", "مرر بثلاثة أصابع لفتح Snap Assist"},
            {"assist_hint_button", "استخدم زر إمكانية الوصول لفتح Snap Assist"},
            {"assist_hint_wave", "مرر يدك مرتين أمام الشاشة لفتح Snap Assist"},
            {"assist_no_proximity", "هذا الجهاز لا يحتوي على حساس قرب"},
            {"assist_hint_volume", "اضغط زر رفع الصوت مرتين بسرعة لفتح Snap Assist"},
            {"assist_trigger_volume", "تم فتح Snap Assist عبر اختصار الصوت"},
            {"assist_triggered", "تم تفعيل Snap Assist"},
            {"assist_ocr_empty", "لم يتم العثور على نص ظاهر على الشاشة"},
            {"assist_select_text_first", "حدد النص أولاً ثم شغّل الأداة"},
            {"assist_invalid_ip", "النص المحدد ليس IP أو Host صالح"},
            {"assist_screenshot_taking", "جارٍ التقاط لقطة الشاشة..."},
            {"assist_screenshot_saved", "تم حفظ اللقطة في Pictures/SnapToolKit"},
            {"assist_screenshot_failed", "فشل التقاط لقطة الشاشة"},
            {"assist_screenshot_unsupported", "التقاط الشاشة يتطلب Android 11 أو أحدث"},
        });

        // French
        add("fr", new String[][]{
            {"no_text",         "Aucun texte sélectionné"},
            {"error",           "Erreur"},
            {"copied",          "Copié"},
            {"close",           "Fermer"},
            {"save",            "Enregistrer"},
            {"saved",           "Enregistré dans Téléchargements"},
            {"shortening",      "Raccourcissement..."},
            {"shorten_error",   "Échec du raccourcissement"},
            {"translating",     "Traduction en cours..."},
            {"translate_error", "Traduction échouée"},
            {"computing",       "Calcul en cours..."},
            {"hash_copied",     "MD5 & SHA256 copiés"},
            {"case_title",      "Changer la casse"},
            {"uppercase",       "MAJUSCULES"},
            {"lowercase",       "minuscules"},
            {"titlecase",       "Première Lettre"},
            {"sentencecase",    "Début de phrase"},
            {"looking_up",      "Recherche..."},
            {"ip_error",        "Impossible d'obtenir les infos IP"},
            {"generating_qr",   "Génération du QR..."},
            {"qr_error",        "Échec de la génération QR"},
            {"select_format",   "Convertir en"},
            {"converting",      "Conversion..."},
            {"convert_done",    "Converti et enregistré"},
            {"convert_error",   "Échec de la conversion"},
        });

        // Spanish
        add("es", new String[][]{
            {"no_text",         "Sin texto seleccionado"},
            {"error",           "Error"},
            {"copied",          "Copiado"},
            {"close",           "Cerrar"},
            {"save",            "Guardar"},
            {"saved",           "Guardado en Descargas"},
            {"shortening",      "Acortando URL..."},
            {"shorten_error",   "Error al acortar URL"},
            {"translating",     "Traduciendo..."},
            {"translate_error", "Traducción fallida"},
            {"computing",       "Calculando..."},
            {"hash_copied",     "MD5 y SHA256 copiados"},
            {"case_title",      "Cambiar mayúsculas"},
            {"uppercase",       "MAYÚSCULAS"},
            {"lowercase",       "minúsculas"},
            {"titlecase",       "Primera Letra"},
            {"sentencecase",    "Inicio de oración"},
            {"looking_up",      "Buscando..."},
            {"ip_error",        "No se pudo obtener info IP"},
            {"generating_qr",   "Generando QR..."},
            {"qr_error",        "Error al generar QR"},
            {"select_format",   "Convertir a"},
            {"converting",      "Convirtiendo..."},
            {"convert_done",    "Convertido y guardado"},
            {"convert_error",   "Conversión fallida"},
        });

        // German
        add("de", new String[][]{
            {"no_text",         "Kein Text ausgewählt"},
            {"error",           "Fehler"},
            {"copied",          "Kopiert"},
            {"close",           "Schließen"},
            {"save",            "Speichern"},
            {"saved",           "In Downloads gespeichert"},
            {"shortening",      "URL wird gekürzt..."},
            {"shorten_error",   "URL-Kürzung fehlgeschlagen"},
            {"translating",     "Übersetzen..."},
            {"translate_error", "Übersetzung fehlgeschlagen"},
            {"computing",       "Wird berechnet..."},
            {"hash_copied",     "MD5 & SHA256 kopiert"},
            {"case_title",      "Groß-/Kleinschreibung"},
            {"uppercase",       "GROSSBUCHSTABEN"},
            {"lowercase",       "kleinbuchstaben"},
            {"titlecase",       "Erster Buchstabe"},
            {"sentencecase",    "Satzanfang"},
            {"looking_up",      "Suche läuft..."},
            {"ip_error",        "IP-Info nicht abrufbar"},
            {"generating_qr",   "QR wird erstellt..."},
            {"qr_error",        "QR-Erstellung fehlgeschlagen"},
            {"select_format",   "Konvertieren zu"},
            {"converting",      "Konvertierung..."},
            {"convert_done",    "Konvertiert und gespeichert"},
            {"convert_error",   "Konvertierung fehlgeschlagen"},
        });

        // Chinese
        add("zh", new String[][]{
            {"no_text",         "未选择文本"},
            {"error",           "错误"},
            {"copied",          "已复制"},
            {"close",           "关闭"},
            {"save",            "保存"},
            {"saved",           "已保存到下载"},
            {"shortening",      "正在缩短链接..."},
            {"shorten_error",   "缩短链接失败"},
            {"translating",     "正在翻译..."},
            {"translate_error", "翻译失败"},
            {"computing",       "计算中..."},
            {"hash_copied",     "MD5和SHA256已复制"},
            {"case_title",      "更改大小写"},
            {"uppercase",       "大写"},
            {"lowercase",       "小写"},
            {"titlecase",       "首字母大写"},
            {"sentencecase",    "句首大写"},
            {"looking_up",      "查询中..."},
            {"ip_error",        "无法获取IP信息"},
            {"generating_qr",   "生成二维码..."},
            {"qr_error",        "二维码生成失败"},
            {"select_format",   "转换为"},
            {"converting",      "转换中..."},
            {"convert_done",    "已转换并保存"},
            {"convert_error",   "转换失败"},
        });

        // Russian
        add("ru", new String[][]{
            {"no_text",         "Текст не выбран"},
            {"error",           "Ошибка"},
            {"copied",          "Скопировано"},
            {"close",           "Закрыть"},
            {"save",            "Сохранить"},
            {"saved",           "Сохранено в Загрузки"},
            {"shortening",      "Сокращение ссылки..."},
            {"shorten_error",   "Не удалось сократить ссылку"},
            {"translating",     "Перевод..."},
            {"translate_error", "Перевод не удался"},
            {"computing",       "Вычисление..."},
            {"hash_copied",     "MD5 и SHA256 скопированы"},
            {"case_title",      "Изменить регистр"},
            {"uppercase",       "ВЕРХНИЙ РЕГИСТР"},
            {"lowercase",       "нижний регистр"},
            {"titlecase",       "Каждое Слово"},
            {"sentencecase",    "Начало предложения"},
            {"looking_up",      "Поиск..."},
            {"ip_error",        "Не удалось получить IP-инфо"},
            {"generating_qr",   "Создание QR..."},
            {"qr_error",        "Не удалось создать QR"},
            {"select_format",   "Конвертировать в"},
            {"converting",      "Конвертация..."},
            {"convert_done",    "Конвертировано и сохранено"},
            {"convert_error",   "Конвертация не удалась"},
        });

        // Turkish
        add("tr", new String[][]{
            {"no_text",         "Metin seçilmedi"},
            {"error",           "Hata"},
            {"copied",          "Kopyalandı"},
            {"close",           "Kapat"},
            {"save",            "Kaydet"},
            {"saved",           "İndirilenler'e kaydedildi"},
            {"shortening",      "URL kısaltılıyor..."},
            {"shorten_error",   "URL kısaltılamadı"},
            {"translating",     "Çevriliyor..."},
            {"translate_error", "Çeviri başarısız"},
            {"computing",       "Hesaplanıyor..."},
            {"hash_copied",     "MD5 ve SHA256 kopyalandı"},
            {"case_title",      "Büyük/Küçük Harf"},
            {"uppercase",       "BÜYÜK HARF"},
            {"lowercase",       "küçük harf"},
            {"titlecase",       "Her Kelimenin Baş Harfi"},
            {"sentencecase",    "Cümle başı"},
            {"looking_up",      "Aranıyor..."},
            {"ip_error",        "IP bilgisi alınamadı"},
            {"generating_qr",   "QR oluşturuluyor..."},
            {"qr_error",        "QR oluşturulamadı"},
            {"select_format",   "Dönüştür"},
            {"converting",      "Dönüştürülüyor..."},
            {"convert_done",    "Dönüştürüldü ve kaydedildi"},
            {"convert_error",   "Dönüştürme başarısız"},
        });

        // Persian
        add("fa", new String[][]{
            {"no_text",         "متنی انتخاب نشده"},
            {"error",           "خطا"},
            {"copied",          "کپی شد"},
            {"close",           "بستن"},
            {"save",            "ذخیره"},
            {"saved",           "در دانلودها ذخیره شد"},
            {"shortening",      "در حال کوتاه کردن..."},
            {"shorten_error",   "خطا در کوتاه کردن لینک"},
            {"translating",     "در حال ترجمه..."},
            {"translate_error", "ترجمه ناموفق"},
            {"computing",       "در حال محاسبه..."},
            {"hash_copied",     "MD5 و SHA256 کپی شد"},
            {"case_title",      "تغییر حروف"},
            {"uppercase",       "حروف بزرگ"},
            {"lowercase",       "حروف کوچک"},
            {"titlecase",       "اول هر کلمه"},
            {"sentencecase",    "اول جمله"},
            {"looking_up",      "جستجو..."},
            {"ip_error",        "دریافت اطلاعات IP ناموفق"},
            {"generating_qr",   "ساخت QR..."},
            {"qr_error",        "ساخت QR ناموفق"},
            {"select_format",   "تبدیل به"},
            {"converting",      "در حال تبدیل..."},
            {"convert_done",    "تبدیل و ذخیره شد"},
            {"convert_error",   "تبدیل ناموفق"},
        });

        // Hindi
        add("hi", new String[][]{
            {"no_text",         "कोई टेक्स्ट नहीं चुना"},
            {"error",           "त्रुटि"},
            {"copied",          "कॉपी हो गया"},
            {"close",           "बंद करें"},
            {"save",            "सहेजें"},
            {"saved",           "Downloads में सहेजा गया"},
            {"shortening",      "URL छोटा हो रहा है..."},
            {"shorten_error",   "URL छोटा करने में विफल"},
            {"translating",     "अनुवाद हो रहा है..."},
            {"translate_error", "अनुवाद विफल"},
            {"computing",       "गणना हो रही है..."},
            {"hash_copied",     "MD5 और SHA256 कॉपी हुआ"},
            {"case_title",      "केस बदलें"},
            {"uppercase",       "UPPERCASE"},
            {"lowercase",       "lowercase"},
            {"titlecase",       "Title Case"},
            {"sentencecase",    "Sentence case"},
            {"looking_up",      "खोज रहा है..."},
            {"ip_error",        "IP जानकारी नहीं मिली"},
            {"generating_qr",   "QR बन रहा है..."},
            {"qr_error",        "QR बनाने में विफल"},
            {"select_format",   "में बदलें"},
            {"converting",      "बदल रहा है..."},
            {"convert_done",    "बदला और सहेजा गया"},
            {"convert_error",   "बदलने में विफल"},
        });

        // Portuguese
        add("pt", new String[][]{
            {"no_text",         "Nenhum texto selecionado"},
            {"error",           "Erro"},
            {"copied",          "Copiado"},
            {"close",           "Fechar"},
            {"save",            "Salvar"},
            {"saved",           "Salvo em Downloads"},
            {"shortening",      "Encurtando URL..."},
            {"shorten_error",   "Falha ao encurtar URL"},
            {"translating",     "Traduzindo..."},
            {"translate_error", "Tradução falhou"},
            {"computing",       "Calculando..."},
            {"hash_copied",     "MD5 e SHA256 copiados"},
            {"case_title",      "Mudar Maiúsculas"},
            {"uppercase",       "MAIÚSCULAS"},
            {"lowercase",       "minúsculas"},
            {"titlecase",       "Primeira Letra"},
            {"sentencecase",    "Início de frase"},
            {"looking_up",      "Buscando..."},
            {"ip_error",        "Falha ao obter info IP"},
            {"generating_qr",   "Gerando QR..."},
            {"qr_error",        "Falha ao gerar QR"},
            {"select_format",   "Converter para"},
            {"converting",      "Convertendo..."},
            {"convert_done",    "Convertido e salvo"},
            {"convert_error",   "Conversão falhou"},
        });

        // Indonesian
        add("id", new String[][]{
            {"no_text",         "Tidak ada teks dipilih"},
            {"error",           "Error"},
            {"copied",          "Disalin"},
            {"close",           "Tutup"},
            {"save",            "Simpan"},
            {"saved",           "Disimpan di Unduhan"},
            {"shortening",      "Mempersingkat URL..."},
            {"shorten_error",   "Gagal mempersingkat URL"},
            {"translating",     "Menerjemahkan..."},
            {"translate_error", "Terjemahan gagal"},
            {"computing",       "Menghitung..."},
            {"hash_copied",     "MD5 & SHA256 disalin"},
            {"case_title",      "Ubah Huruf"},
            {"uppercase",       "HURUF BESAR"},
            {"lowercase",       "huruf kecil"},
            {"titlecase",       "Huruf Depan Besar"},
            {"sentencecase",    "Awal kalimat"},
            {"looking_up",      "Mencari..."},
            {"ip_error",        "Info IP tidak dapat diambil"},
            {"generating_qr",   "Membuat QR..."},
            {"qr_error",        "Gagal membuat QR"},
            {"select_format",   "Konversi ke"},
            {"converting",      "Mengonversi..."},
            {"convert_done",    "Dikonversi dan disimpan"},
            {"convert_error",   "Konversi gagal"},
        });

        // Japanese
        add("ja", new String[][]{
            {"no_text",         "テキストが選択されていません"},
            {"error",           "エラー"},
            {"copied",          "コピーしました"},
            {"close",           "閉じる"},
            {"save",            "保存"},
            {"saved",           "ダウンロードに保存しました"},
            {"shortening",      "URL短縮中..."},
            {"shorten_error",   "URL短縮に失敗しました"},
            {"translating",     "翻訳中..."},
            {"translate_error", "翻訳に失敗しました"},
            {"computing",       "計算中..."},
            {"hash_copied",     "MD5とSHA256をコピーしました"},
            {"case_title",      "大文字小文字変換"},
            {"uppercase",       "大文字"},
            {"lowercase",       "小文字"},
            {"titlecase",       "単語の先頭を大文字"},
            {"sentencecase",    "文頭を大文字"},
            {"looking_up",      "検索中..."},
            {"ip_error",        "IP情報を取得できません"},
            {"generating_qr",   "QR生成中..."},
            {"qr_error",        "QR生成に失敗しました"},
            {"select_format",   "変換先"},
            {"converting",      "変換中..."},
            {"convert_done",    "変換して保存しました"},
            {"convert_error",   "変換に失敗しました"},
        });

        // Korean
        add("ko", new String[][]{
            {"no_text",         "선택된 텍스트 없음"},
            {"error",           "오류"},
            {"copied",          "복사됨"},
            {"close",           "닫기"},
            {"save",            "저장"},
            {"saved",           "다운로드에 저장됨"},
            {"shortening",      "URL 단축 중..."},
            {"shorten_error",   "URL 단축 실패"},
            {"translating",     "번역 중..."},
            {"translate_error", "번역 실패"},
            {"computing",       "계산 중..."},
            {"hash_copied",     "MD5 및 SHA256 복사됨"},
            {"case_title",      "대소문자 변환"},
            {"uppercase",       "대문자"},
            {"lowercase",       "소문자"},
            {"titlecase",       "단어 첫 글자 대문자"},
            {"sentencecase",    "문장 첫 글자 대문자"},
            {"looking_up",      "검색 중..."},
            {"ip_error",        "IP 정보를 가져올 수 없음"},
            {"generating_qr",   "QR 생성 중..."},
            {"qr_error",        "QR 생성 실패"},
            {"select_format",   "변환 대상"},
            {"converting",      "변환 중..."},
            {"convert_done",    "변환 및 저장됨"},
            {"convert_error",   "변환 실패"},
        });
    }

    public static String get(String key) {
        String lang = Locale.getDefault().getLanguage();
        HashMap<String, String> map = data.containsKey(lang) ? data.get(lang) : null;
        HashMap<String, String> en = data.get("en");
        String val = map != null ? map.get(key) : null;
        if (val != null) return val;
        if (en != null && en.containsKey(key)) return en.get(key);
        return key;
    }

    private static void add(String lang, String[][] pairs) {
        HashMap<String, String> map = new HashMap<>();
        for (String[] p : pairs) map.put(p[0], p[1]);
        data.put(lang, map);
    }
}
